import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FronteggAppProvider } from "@frontegg/nextjs/app";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const authOptions = {
        keepSessionAlive: true,
    };

    return (
        <html lang="en" className="h-full">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
                <FronteggAppProvider authOptions={authOptions} customLoader={true}>
                    <div className="h-full">{children}</div>
                </FronteggAppProvider>
            </body>
        </html>
    );
}
