name: Frontend Tests

on:
  push:
    branches: [main]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  test:
    name: Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: apps/frontend

      - name: Run Linting
        run: npm run lint
        working-directory: apps/frontend

      - name: Run Type Check
        run: npm run type-check
        working-directory: apps/frontend

      - name: Run Tests
        run: npm run test
        working-directory: apps/frontend

      - name: Build Check
        run: npm run build
        working-directory: apps/frontend
        env:
          NEXT_PUBLIC_API_URL: https://staging-api.get-convinced.com
          NEXT_PUBLIC_FRONTEGG_CLIENT_ID: test-client-id
